/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsResponseMetrics
 */
export interface AnalyticsResponseMetrics {
    /**
     * Сумма доходов за период
     * @type {string}
     * @memberof AnalyticsResponseMetrics
     */
    income?: string;
    /**
     * Сумма расходов за период
     * @type {string}
     * @memberof AnalyticsResponseMetrics
     */
    expense?: string;
    /**
     * Итоговый баланс
     * @type {string}
     * @memberof AnalyticsResponseMetrics
     */
    balance?: string;
}

/**
 * Check if a given object implements the AnalyticsResponseMetrics interface.
 */
export function instanceOfAnalyticsResponseMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsResponseMetricsFromJSON(json: any): AnalyticsResponseMetrics {
    return AnalyticsResponseMetricsFromJSONTyped(json, false);
}

export function AnalyticsResponseMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponseMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'income': !exists(json, 'income') ? undefined : json['income'],
        'expense': !exists(json, 'expense') ? undefined : json['expense'],
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
    };
}

export function AnalyticsResponseMetricsToJSON(value?: AnalyticsResponseMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'income': value.income,
        'expense': value.expense,
        'balance': value.balance,
    };
}

