/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalyticsResponseMetrics } from './AnalyticsResponseMetrics';
import {
    AnalyticsResponseMetricsFromJSON,
    AnalyticsResponseMetricsFromJSONTyped,
    AnalyticsResponseMetricsToJSON,
} from './AnalyticsResponseMetrics';
import type { TransactionDto } from './TransactionDto';
import {
    TransactionDtoFromJSON,
    TransactionDtoFromJSONTyped,
    TransactionDtoToJSON,
} from './TransactionDto';

/**
 * 
 * @export
 * @interface AnalyticsResponse
 */
export interface AnalyticsResponse {
    /**
     * 
     * @type {AnalyticsResponseMetrics}
     * @memberof AnalyticsResponse
     */
    metrics?: AnalyticsResponseMetrics;
    /**
     * Код валюты ISO-4217
     * @type {string}
     * @memberof AnalyticsResponse
     */
    currency?: string;
    /**
     * 
     * @type {Array<TransactionDto>}
     * @memberof AnalyticsResponse
     */
    recentTransactions?: Array<TransactionDto>;
}

/**
 * Check if a given object implements the AnalyticsResponse interface.
 */
export function instanceOfAnalyticsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsResponseFromJSON(json: any): AnalyticsResponse {
    return AnalyticsResponseFromJSONTyped(json, false);
}

export function AnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metrics': !exists(json, 'metrics') ? undefined : AnalyticsResponseMetricsFromJSON(json['metrics']),
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'recentTransactions': !exists(json, 'recentTransactions') ? undefined : ((json['recentTransactions'] as Array<any>).map(TransactionDtoFromJSON)),
    };
}

export function AnalyticsResponseToJSON(value?: AnalyticsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metrics': AnalyticsResponseMetricsToJSON(value.metrics),
        'currency': value.currency,
        'recentTransactions': value.recentTransactions === undefined ? undefined : ((value.recentTransactions as Array<any>).map(TransactionDtoToJSON)),
    };
}

