/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryIconDto
 */
export interface CategoryIconDto {
    /**
     * 
     * @type {string}
     * @memberof CategoryIconDto
     */
    id?: string;
    /**
     * Название иконки
     * @type {string}
     * @memberof CategoryIconDto
     */
    name?: string;
    /**
     * Unicode символ
     * @type {string}
     * @memberof CategoryIconDto
     */
    unicode?: string;
    /**
     * Категория иконки
     * @type {string}
     * @memberof CategoryIconDto
     */
    category?: string;
}

/**
 * Check if a given object implements the CategoryIconDto interface.
 */
export function instanceOfCategoryIconDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryIconDtoFromJSON(json: any): CategoryIconDto {
    return CategoryIconDtoFromJSONTyped(json, false);
}

export function CategoryIconDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryIconDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'unicode': !exists(json, 'unicode') ? undefined : json['unicode'],
        'category': !exists(json, 'category') ? undefined : json['category'],
    };
}

export function CategoryIconDtoToJSON(value?: CategoryIconDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'unicode': value.unicode,
        'category': value.category,
    };
}

