/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryAnalyticsResponseCategoriesInner } from './CategoryAnalyticsResponseCategoriesInner';
import {
    CategoryAnalyticsResponseCategoriesInnerFromJSON,
    CategoryAnalyticsResponseCategoriesInnerFromJSONTyped,
    CategoryAnalyticsResponseCategoriesInnerToJSON,
} from './CategoryAnalyticsResponseCategoriesInner';

/**
 * 
 * @export
 * @interface CategoryAnalyticsResponse
 */
export interface CategoryAnalyticsResponse {
    /**
     * 
     * @type {Array<CategoryAnalyticsResponseCategoriesInner>}
     * @memberof CategoryAnalyticsResponse
     */
    categories?: Array<CategoryAnalyticsResponseCategoriesInner>;
    /**
     * 
     * @type {string}
     * @memberof CategoryAnalyticsResponse
     */
    totalAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryAnalyticsResponse
     */
    currency?: string;
}

/**
 * Check if a given object implements the CategoryAnalyticsResponse interface.
 */
export function instanceOfCategoryAnalyticsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryAnalyticsResponseFromJSON(json: any): CategoryAnalyticsResponse {
    return CategoryAnalyticsResponseFromJSONTyped(json, false);
}

export function CategoryAnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryAnalyticsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': !exists(json, 'categories') ? undefined : ((json['categories'] as Array<any>).map(CategoryAnalyticsResponseCategoriesInnerFromJSON)),
        'totalAmount': !exists(json, 'totalAmount') ? undefined : json['totalAmount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
    };
}

export function CategoryAnalyticsResponseToJSON(value?: CategoryAnalyticsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': value.categories === undefined ? undefined : ((value.categories as Array<any>).map(CategoryAnalyticsResponseCategoriesInnerToJSON)),
        'totalAmount': value.totalAmount,
        'currency': value.currency,
    };
}

