/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryIconsResponseCategoriesInner } from './CategoryIconsResponseCategoriesInner';
import {
    CategoryIconsResponseCategoriesInnerFromJSON,
    CategoryIconsResponseCategoriesInnerFromJSONTyped,
    CategoryIconsResponseCategoriesInnerToJSON,
} from './CategoryIconsResponseCategoriesInner';

/**
 * 
 * @export
 * @interface CategoryIconsResponse
 */
export interface CategoryIconsResponse {
    /**
     * 
     * @type {Array<CategoryIconsResponseCategoriesInner>}
     * @memberof CategoryIconsResponse
     */
    categories?: Array<CategoryIconsResponseCategoriesInner>;
}

/**
 * Check if a given object implements the CategoryIconsResponse interface.
 */
export function instanceOfCategoryIconsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryIconsResponseFromJSON(json: any): CategoryIconsResponse {
    return CategoryIconsResponseFromJSONTyped(json, false);
}

export function CategoryIconsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryIconsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': !exists(json, 'categories') ? undefined : ((json['categories'] as Array<any>).map(CategoryIconsResponseCategoriesInnerFromJSON)),
    };
}

export function CategoryIconsResponseToJSON(value?: CategoryIconsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': value.categories === undefined ? undefined : ((value.categories as Array<any>).map(CategoryIconsResponseCategoriesInnerToJSON)),
    };
}

