/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryType } from './CategoryType';
import {
    CategoryTypeFromJSON,
    CategoryTypeFromJSONTyped,
    CategoryTypeToJSON,
} from './CategoryType';

/**
 * 
 * @export
 * @interface CategoryDto
 */
export interface CategoryDto {
    /**
     * ID категории
     * @type {string}
     * @memberof CategoryDto
     */
    id?: string;
    /**
     * Название категории
     * @type {string}
     * @memberof CategoryDto
     */
    name?: string;
    /**
     * 
     * @type {CategoryType}
     * @memberof CategoryDto
     */
    type?: CategoryType;
    /**
     * ID родительской категории
     * @type {string}
     * @memberof CategoryDto
     */
    parentId?: string | null;
    /**
     * Иконка категории
     * @type {string}
     * @memberof CategoryDto
     */
    icon?: string | null;
    /**
     * Цвет иконки в HEX-формате
     * @type {string}
     * @memberof CategoryDto
     */
    iconColor?: string | null;
    /**
     * Порядок отображения категории (меньше = выше в списке)
     * @type {number}
     * @memberof CategoryDto
     */
    displayOrder?: number;
    /**
     * Список вложенных подкатегорий
     * @type {Array<CategoryDto>}
     * @memberof CategoryDto
     */
    children?: Array<CategoryDto>;
}

/**
 * Check if a given object implements the CategoryDto interface.
 */
export function instanceOfCategoryDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryDtoFromJSON(json: any): CategoryDto {
    return CategoryDtoFromJSONTyped(json, false);
}

export function CategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : CategoryTypeFromJSON(json['type']),
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'iconColor': !exists(json, 'iconColor') ? undefined : json['iconColor'],
        'displayOrder': !exists(json, 'displayOrder') ? undefined : json['displayOrder'],
        'children': !exists(json, 'children') ? undefined : ((json['children'] as Array<any>).map(CategoryDtoFromJSON)),
    };
}

export function CategoryDtoToJSON(value?: CategoryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': CategoryTypeToJSON(value.type),
        'parentId': value.parentId,
        'icon': value.icon,
        'iconColor': value.iconColor,
        'displayOrder': value.displayOrder,
        'children': value.children === undefined ? undefined : ((value.children as Array<any>).map(CategoryDtoToJSON)),
    };
}

