/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryAnalyticsResponseCategoriesInner
 */
export interface CategoryAnalyticsResponseCategoriesInner {
    /**
     * 
     * @type {string}
     * @memberof CategoryAnalyticsResponseCategoriesInner
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryAnalyticsResponseCategoriesInner
     */
    categoryName?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryAnalyticsResponseCategoriesInner
     */
    amount?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryAnalyticsResponseCategoriesInner
     */
    percentage?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryAnalyticsResponseCategoriesInner
     */
    transactionCount?: number;
}

/**
 * Check if a given object implements the CategoryAnalyticsResponseCategoriesInner interface.
 */
export function instanceOfCategoryAnalyticsResponseCategoriesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryAnalyticsResponseCategoriesInnerFromJSON(json: any): CategoryAnalyticsResponseCategoriesInner {
    return CategoryAnalyticsResponseCategoriesInnerFromJSONTyped(json, false);
}

export function CategoryAnalyticsResponseCategoriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryAnalyticsResponseCategoriesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'categoryName': !exists(json, 'categoryName') ? undefined : json['categoryName'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'percentage': !exists(json, 'percentage') ? undefined : json['percentage'],
        'transactionCount': !exists(json, 'transactionCount') ? undefined : json['transactionCount'],
    };
}

export function CategoryAnalyticsResponseCategoriesInnerToJSON(value?: CategoryAnalyticsResponseCategoriesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryId': value.categoryId,
        'categoryName': value.categoryName,
        'amount': value.amount,
        'percentage': value.percentage,
        'transactionCount': value.transactionCount,
    };
}

