/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип категории
 * @export
 */
export const CategoryType = {
    Income: 'INCOME',
    Expense: 'EXPENSE'
} as const;
export type CategoryType = typeof CategoryType[keyof typeof CategoryType];


export function CategoryTypeFromJSON(json: any): CategoryType {
    return CategoryTypeFromJSONTyped(json, false);
}

export function CategoryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryType {
    return json as CategoryType;
}

export function CategoryTypeToJSON(value?: CategoryType | null): any {
    return value as any;
}

