/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordResponse
 */
export interface ChangePasswordResponse {
    /**
     * Флаг успешного изменения пароля
     * @type {boolean}
     * @memberof ChangePasswordResponse
     */
    success?: boolean;
    /**
     * Сообщение об успешном изменении пароля
     * @type {string}
     * @memberof ChangePasswordResponse
     */
    message?: string;
    /**
     * Дата и время изменения пароля
     * @type {Date}
     * @memberof ChangePasswordResponse
     */
    changedAt?: Date;
    /**
     * Новый JWT токен, если требуется обновление сессии
     * @type {string}
     * @memberof ChangePasswordResponse
     */
    newToken?: string | null;
}

/**
 * Check if a given object implements the ChangePasswordResponse interface.
 */
export function instanceOfChangePasswordResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChangePasswordResponseFromJSON(json: any): ChangePasswordResponse {
    return ChangePasswordResponseFromJSONTyped(json, false);
}

export function ChangePasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'changedAt': !exists(json, 'changedAt') ? undefined : (new Date(json['changedAt'])),
        'newToken': !exists(json, 'newToken') ? undefined : json['newToken'],
    };
}

export function ChangePasswordResponseToJSON(value?: ChangePasswordResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'changedAt': value.changedAt === undefined ? undefined : (value.changedAt.toISOString()),
        'newToken': value.newToken,
    };
}

