/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryType } from './CategoryType';
import {
    CategoryTypeFromJSON,
    CategoryTypeFromJSONTyped,
    CategoryTypeToJSON,
} from './CategoryType';

/**
 * 
 * @export
 * @interface CreateCategoryRequest
 */
export interface CreateCategoryRequest {
    /**
     * Название категории
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    name: string;
    /**
     * 
     * @type {CategoryType}
     * @memberof CreateCategoryRequest
     */
    type: CategoryType;
    /**
     * ID родительской категории
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    parentId?: string | null;
    /**
     * Иконка категории
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    icon?: string | null;
    /**
     * Цвет иконки в HEX-формате
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    iconColor?: string | null;
}

/**
 * Check if a given object implements the CreateCategoryRequest interface.
 */
export function instanceOfCreateCategoryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function CreateCategoryRequestFromJSON(json: any): CreateCategoryRequest {
    return CreateCategoryRequestFromJSONTyped(json, false);
}

export function CreateCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': CategoryTypeFromJSON(json['type']),
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'iconColor': !exists(json, 'iconColor') ? undefined : json['iconColor'],
    };
}

export function CreateCategoryRequestToJSON(value?: CreateCategoryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': CategoryTypeToJSON(value.type),
        'parentId': value.parentId,
        'icon': value.icon,
        'iconColor': value.iconColor,
    };
}

