/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InputType } from './InputType';
import {
    InputTypeFromJSON,
    InputTypeFromJSONTyped,
    InputTypeToJSON,
} from './InputType';
import type { TransactionType } from './TransactionType';
import {
    TransactionTypeFromJSON,
    TransactionTypeFromJSONTyped,
    TransactionTypeToJSON,
} from './TransactionType';

/**
 * 
 * @export
 * @interface CreateTransactionRequest
 */
export interface CreateTransactionRequest {
    /**
     * Сумма транзакции в формате decimal string (копейки)
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    amount: string;
    /**
     * Код валюты ISO-4217
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    currency?: string;
    /**
     * Дата транзакции
     * @type {Date}
     * @memberof CreateTransactionRequest
     */
    date?: Date;
    /**
     * ID категории
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    categoryId: string;
    /**
     * Название транзакции
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    name: string;
    /**
     * Подробное описание транзакции
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    description?: string;
    /**
     * 
     * @type {TransactionType}
     * @memberof CreateTransactionRequest
     */
    type: TransactionType;
    /**
     * 
     * @type {InputType}
     * @memberof CreateTransactionRequest
     */
    inputType?: InputType;
    /**
     * ID счета
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    accountId: string;
    /**
     * Исключить из расчетов
     * @type {boolean}
     * @memberof CreateTransactionRequest
     */
    excluded?: boolean;
}

/**
 * Check if a given object implements the CreateTransactionRequest interface.
 */
export function instanceOfCreateTransactionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "categoryId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "accountId" in value;

    return isInstance;
}

export function CreateTransactionRequestFromJSON(json: any): CreateTransactionRequest {
    return CreateTransactionRequestFromJSONTyped(json, false);
}

export function CreateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'categoryId': json['categoryId'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': TransactionTypeFromJSON(json['type']),
        'inputType': !exists(json, 'inputType') ? undefined : InputTypeFromJSON(json['inputType']),
        'accountId': json['accountId'],
        'excluded': !exists(json, 'excluded') ? undefined : json['excluded'],
    };
}

export function CreateTransactionRequestToJSON(value?: CreateTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': value.currency,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
        'categoryId': value.categoryId,
        'name': value.name,
        'description': value.description,
        'type': TransactionTypeToJSON(value.type),
        'inputType': InputTypeToJSON(value.inputType),
        'accountId': value.accountId,
        'excluded': value.excluded,
    };
}

