/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyTransactionsResponseDaysInner
 */
export interface DailyTransactionsResponseDaysInner {
    /**
     * 
     * @type {Date}
     * @memberof DailyTransactionsResponseDaysInner
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof DailyTransactionsResponseDaysInner
     */
    income?: string;
    /**
     * 
     * @type {string}
     * @memberof DailyTransactionsResponseDaysInner
     */
    expense?: string;
    /**
     * 
     * @type {number}
     * @memberof DailyTransactionsResponseDaysInner
     */
    transactionCount?: number;
}

/**
 * Check if a given object implements the DailyTransactionsResponseDaysInner interface.
 */
export function instanceOfDailyTransactionsResponseDaysInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DailyTransactionsResponseDaysInnerFromJSON(json: any): DailyTransactionsResponseDaysInner {
    return DailyTransactionsResponseDaysInnerFromJSONTyped(json, false);
}

export function DailyTransactionsResponseDaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyTransactionsResponseDaysInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'income': !exists(json, 'income') ? undefined : json['income'],
        'expense': !exists(json, 'expense') ? undefined : json['expense'],
        'transactionCount': !exists(json, 'transactionCount') ? undefined : json['transactionCount'],
    };
}

export function DailyTransactionsResponseDaysInnerToJSON(value?: DailyTransactionsResponseDaysInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
        'income': value.income,
        'expense': value.expense,
        'transactionCount': value.transactionCount,
    };
}

