/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DailyTransactionsResponseDaysInner } from './DailyTransactionsResponseDaysInner';
import {
    DailyTransactionsResponseDaysInnerFromJSON,
    DailyTransactionsResponseDaysInnerFromJSONTyped,
    DailyTransactionsResponseDaysInnerToJSON,
} from './DailyTransactionsResponseDaysInner';

/**
 * 
 * @export
 * @interface DailyTransactionsResponse
 */
export interface DailyTransactionsResponse {
    /**
     * 
     * @type {Array<DailyTransactionsResponseDaysInner>}
     * @memberof DailyTransactionsResponse
     */
    days?: Array<DailyTransactionsResponseDaysInner>;
    /**
     * 
     * @type {string}
     * @memberof DailyTransactionsResponse
     */
    currency?: string;
}

/**
 * Check if a given object implements the DailyTransactionsResponse interface.
 */
export function instanceOfDailyTransactionsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DailyTransactionsResponseFromJSON(json: any): DailyTransactionsResponse {
    return DailyTransactionsResponseFromJSONTyped(json, false);
}

export function DailyTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyTransactionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'days': !exists(json, 'days') ? undefined : ((json['days'] as Array<any>).map(DailyTransactionsResponseDaysInnerFromJSON)),
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
    };
}

export function DailyTransactionsResponseToJSON(value?: DailyTransactionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'days': value.days === undefined ? undefined : ((value.days as Array<any>).map(DailyTransactionsResponseDaysInnerToJSON)),
        'currency': value.currency,
    };
}

