/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryType } from './CategoryType';
import {
    CategoryTypeFromJSON,
    CategoryTypeFromJSONTyped,
    CategoryTypeToJSON,
} from './CategoryType';

/**
 * 
 * @export
 * @interface DefaultCategoryDto
 */
export interface DefaultCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof DefaultCategoryDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DefaultCategoryDto
     */
    name?: string;
    /**
     * 
     * @type {CategoryType}
     * @memberof DefaultCategoryDto
     */
    type?: CategoryType;
    /**
     * 
     * @type {string}
     * @memberof DefaultCategoryDto
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefaultCategoryDto
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefaultCategoryDto
     */
    parentId?: string | null;
}

/**
 * Check if a given object implements the DefaultCategoryDto interface.
 */
export function instanceOfDefaultCategoryDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DefaultCategoryDtoFromJSON(json: any): DefaultCategoryDto {
    return DefaultCategoryDtoFromJSONTyped(json, false);
}

export function DefaultCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultCategoryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : CategoryTypeFromJSON(json['type']),
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
    };
}

export function DefaultCategoryDtoToJSON(value?: DefaultCategoryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': CategoryTypeToJSON(value.type),
        'icon': value.icon,
        'color': value.color,
        'parentId': value.parentId,
    };
}

