/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportError
 */
export interface ImportError {
    /**
     * Номер строки
     * @type {number}
     * @memberof ImportError
     */
    row?: number;
    /**
     * Поле с ошибкой
     * @type {string}
     * @memberof ImportError
     */
    field?: string;
    /**
     * Сообщение об ошибке
     * @type {string}
     * @memberof ImportError
     */
    message?: string;
    /**
     * Значение, вызвавшее ошибку
     * @type {string}
     * @memberof ImportError
     */
    value?: string;
}

/**
 * Check if a given object implements the ImportError interface.
 */
export function instanceOfImportError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImportErrorFromJSON(json: any): ImportError {
    return ImportErrorFromJSONTyped(json, false);
}

export function ImportErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'row': !exists(json, 'row') ? undefined : json['row'],
        'field': !exists(json, 'field') ? undefined : json['field'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ImportErrorToJSON(value?: ImportError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'row': value.row,
        'field': value.field,
        'message': value.message,
        'value': value.value,
    };
}

