/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportWarning
 */
export interface ImportWarning {
    /**
     * 
     * @type {number}
     * @memberof ImportWarning
     */
    row?: number;
    /**
     * 
     * @type {string}
     * @memberof ImportWarning
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportWarning
     */
    suggestion?: string;
}

/**
 * Check if a given object implements the ImportWarning interface.
 */
export function instanceOfImportWarning(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImportWarningFromJSON(json: any): ImportWarning {
    return ImportWarningFromJSONTyped(json, false);
}

export function ImportWarningFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportWarning {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'row': !exists(json, 'row') ? undefined : json['row'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'suggestion': !exists(json, 'suggestion') ? undefined : json['suggestion'],
    };
}

export function ImportWarningToJSON(value?: ImportWarning | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'row': value.row,
        'message': value.message,
        'suggestion': value.suggestion,
    };
}

