/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип ввода транзакции
 * @export
 */
export const InputType = {
    Manual: 'MANUAL',
    Import: 'IMPORT',
    ReceiptScan: 'RECEIPT_SCAN'
} as const;
export type InputType = typeof InputType[keyof typeof InputType];


export function InputTypeFromJSON(json: any): InputType {
    return InputTypeFromJSONTyped(json, false);
}

export function InputTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputType {
    return json as InputType;
}

export function InputTypeToJSON(value?: InputType | null): any {
    return value as any;
}

