/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PagedTransactionsResponseSort
 */
export interface PagedTransactionsResponseSort {
    /**
     * Отсутствует ли сортировка
     * @type {boolean}
     * @memberof PagedTransactionsResponseSort
     */
    empty?: boolean;
    /**
     * Применена ли сортировка
     * @type {boolean}
     * @memberof PagedTransactionsResponseSort
     */
    sorted?: boolean;
    /**
     * Не применена ли сортировка
     * @type {boolean}
     * @memberof PagedTransactionsResponseSort
     */
    unsorted?: boolean;
}

/**
 * Check if a given object implements the PagedTransactionsResponseSort interface.
 */
export function instanceOfPagedTransactionsResponseSort(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagedTransactionsResponseSortFromJSON(json: any): PagedTransactionsResponseSort {
    return PagedTransactionsResponseSortFromJSONTyped(json, false);
}

export function PagedTransactionsResponseSortFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedTransactionsResponseSort {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
        'sorted': !exists(json, 'sorted') ? undefined : json['sorted'],
        'unsorted': !exists(json, 'unsorted') ? undefined : json['unsorted'],
    };
}

export function PagedTransactionsResponseSortToJSON(value?: PagedTransactionsResponseSort | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'empty': value.empty,
        'sorted': value.sorted,
        'unsorted': value.unsorted,
    };
}

