/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReceiptResponse } from './ReceiptResponse';
import {
    ReceiptResponseFromJSON,
    ReceiptResponseFromJSONTyped,
    ReceiptResponseToJSON,
} from './ReceiptResponse';

/**
 * 
 * @export
 * @interface PagedReceiptResponse
 */
export interface PagedReceiptResponse {
    /**
     * 
     * @type {Array<ReceiptResponse>}
     * @memberof PagedReceiptResponse
     */
    content?: Array<ReceiptResponse>;
    /**
     * 
     * @type {number}
     * @memberof PagedReceiptResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedReceiptResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedReceiptResponse
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedReceiptResponse
     */
    size?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagedReceiptResponse
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedReceiptResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PagedReceiptResponse interface.
 */
export function instanceOfPagedReceiptResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagedReceiptResponseFromJSON(json: any): PagedReceiptResponse {
    return PagedReceiptResponseFromJSONTyped(json, false);
}

export function PagedReceiptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedReceiptResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(ReceiptResponseFromJSON)),
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'first': !exists(json, 'first') ? undefined : json['first'],
        'last': !exists(json, 'last') ? undefined : json['last'],
    };
}

export function PagedReceiptResponseToJSON(value?: PagedReceiptResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(ReceiptResponseToJSON)),
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
        'number': value.number,
        'size': value.size,
        'first': value.first,
        'last': value.last,
    };
}

