/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PeriodSummaryResponsePeriodsInner } from './PeriodSummaryResponsePeriodsInner';
import {
    PeriodSummaryResponsePeriodsInnerFromJSON,
    PeriodSummaryResponsePeriodsInnerFromJSONTyped,
    PeriodSummaryResponsePeriodsInnerToJSON,
} from './PeriodSummaryResponsePeriodsInner';

/**
 * 
 * @export
 * @interface PeriodSummaryResponse
 */
export interface PeriodSummaryResponse {
    /**
     * 
     * @type {Array<PeriodSummaryResponsePeriodsInner>}
     * @memberof PeriodSummaryResponse
     */
    periods?: Array<PeriodSummaryResponsePeriodsInner>;
    /**
     * 
     * @type {string}
     * @memberof PeriodSummaryResponse
     */
    currency?: string;
}

/**
 * Check if a given object implements the PeriodSummaryResponse interface.
 */
export function instanceOfPeriodSummaryResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PeriodSummaryResponseFromJSON(json: any): PeriodSummaryResponse {
    return PeriodSummaryResponseFromJSONTyped(json, false);
}

export function PeriodSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriodSummaryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'periods': !exists(json, 'periods') ? undefined : ((json['periods'] as Array<any>).map(PeriodSummaryResponsePeriodsInnerFromJSON)),
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
    };
}

export function PeriodSummaryResponseToJSON(value?: PeriodSummaryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'periods': value.periods === undefined ? undefined : ((value.periods as Array<any>).map(PeriodSummaryResponsePeriodsInnerToJSON)),
        'currency': value.currency,
    };
}

