/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PeriodSummaryResponsePeriodsInner
 */
export interface PeriodSummaryResponsePeriodsInner {
    /**
     * Месяц в формате YYYY-MM
     * @type {Date}
     * @memberof PeriodSummaryResponsePeriodsInner
     */
    period?: Date;
    /**
     * 
     * @type {string}
     * @memberof PeriodSummaryResponsePeriodsInner
     */
    income?: string;
    /**
     * 
     * @type {string}
     * @memberof PeriodSummaryResponsePeriodsInner
     */
    expense?: string;
    /**
     * 
     * @type {string}
     * @memberof PeriodSummaryResponsePeriodsInner
     */
    balance?: string;
}

/**
 * Check if a given object implements the PeriodSummaryResponsePeriodsInner interface.
 */
export function instanceOfPeriodSummaryResponsePeriodsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PeriodSummaryResponsePeriodsInnerFromJSON(json: any): PeriodSummaryResponsePeriodsInner {
    return PeriodSummaryResponsePeriodsInnerFromJSONTyped(json, false);
}

export function PeriodSummaryResponsePeriodsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriodSummaryResponsePeriodsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'period': !exists(json, 'period') ? undefined : (new Date(json['period'])),
        'income': !exists(json, 'income') ? undefined : json['income'],
        'expense': !exists(json, 'expense') ? undefined : json['expense'],
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
    };
}

export function PeriodSummaryResponsePeriodsInnerToJSON(value?: PeriodSummaryResponsePeriodsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'period': value.period === undefined ? undefined : (value.period.toISOString().substring(0,10)),
        'income': value.income,
        'expense': value.expense,
        'balance': value.balance,
    };
}

