/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProblemDetailsErrorsInner
 */
export interface ProblemDetailsErrorsInner {
    /**
     * Поле с ошибкой
     * @type {string}
     * @memberof ProblemDetailsErrorsInner
     */
    field?: string;
    /**
     * Сообщение об ошибке
     * @type {string}
     * @memberof ProblemDetailsErrorsInner
     */
    message?: string;
    /**
     * Код ошибки
     * @type {string}
     * @memberof ProblemDetailsErrorsInner
     */
    code?: string;
}

/**
 * Check if a given object implements the ProblemDetailsErrorsInner interface.
 */
export function instanceOfProblemDetailsErrorsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProblemDetailsErrorsInnerFromJSON(json: any): ProblemDetailsErrorsInner {
    return ProblemDetailsErrorsInnerFromJSONTyped(json, false);
}

export function ProblemDetailsErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetailsErrorsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': !exists(json, 'field') ? undefined : json['field'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function ProblemDetailsErrorsInnerToJSON(value?: ProblemDetailsErrorsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'message': value.message,
        'code': value.code,
    };
}

