/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptResponse
 */
export interface ReceiptResponse {
    /**
     * 
     * @type {string}
     * @memberof ReceiptResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptResponse
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptResponse
     */
    originalFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptResponse
     */
    contentType?: string;
    /**
     * 
     * @type {number}
     * @memberof ReceiptResponse
     */
    fileSize?: number;
    /**
     * 
     * @type {Date}
     * @memberof ReceiptResponse
     */
    uploadedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ReceiptResponse
     */
    transactionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReceiptResponse
     */
    description?: string | null;
    /**
     * URL для скачивания
     * @type {string}
     * @memberof ReceiptResponse
     */
    downloadUrl?: string;
}

/**
 * Check if a given object implements the ReceiptResponse interface.
 */
export function instanceOfReceiptResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReceiptResponseFromJSON(json: any): ReceiptResponse {
    return ReceiptResponseFromJSONTyped(json, false);
}

export function ReceiptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'originalFilename': !exists(json, 'originalFilename') ? undefined : json['originalFilename'],
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'fileSize': !exists(json, 'fileSize') ? undefined : json['fileSize'],
        'uploadedAt': !exists(json, 'uploadedAt') ? undefined : (new Date(json['uploadedAt'])),
        'transactionId': !exists(json, 'transactionId') ? undefined : json['transactionId'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'downloadUrl': !exists(json, 'downloadUrl') ? undefined : json['downloadUrl'],
    };
}

export function ReceiptResponseToJSON(value?: ReceiptResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'filename': value.filename,
        'originalFilename': value.originalFilename,
        'contentType': value.contentType,
        'fileSize': value.fileSize,
        'uploadedAt': value.uploadedAt === undefined ? undefined : (value.uploadedAt.toISOString()),
        'transactionId': value.transactionId,
        'description': value.description,
        'downloadUrl': value.downloadUrl,
    };
}

