/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InputType } from './InputType';
import {
    InputTypeFromJSON,
    InputTypeFromJSONTyped,
    InputTypeToJSON,
} from './InputType';
import type { TransactionType } from './TransactionType';
import {
    TransactionTypeFromJSON,
    TransactionTypeFromJSONTyped,
    TransactionTypeToJSON,
} from './TransactionType';

/**
 * 
 * @export
 * @interface TransactionDto
 */
export interface TransactionDto {
    /**
     * ID транзакции
     * @type {string}
     * @memberof TransactionDto
     */
    id?: string;
    /**
     * Сумма транзакции в формате decimal string (копейки)
     * @type {string}
     * @memberof TransactionDto
     */
    amount?: string;
    /**
     * Код валюты ISO-4217
     * @type {string}
     * @memberof TransactionDto
     */
    currency?: string;
    /**
     * Дата транзакции
     * @type {Date}
     * @memberof TransactionDto
     */
    date?: Date;
    /**
     * ID категории
     * @type {string}
     * @memberof TransactionDto
     */
    categoryId?: string;
    /**
     * Название транзакции
     * @type {string}
     * @memberof TransactionDto
     */
    name?: string;
    /**
     * Подробное описание транзакции
     * @type {string}
     * @memberof TransactionDto
     */
    description?: string;
    /**
     * 
     * @type {TransactionType}
     * @memberof TransactionDto
     */
    type?: TransactionType;
    /**
     * 
     * @type {InputType}
     * @memberof TransactionDto
     */
    inputType?: InputType;
    /**
     * ID счета
     * @type {string}
     * @memberof TransactionDto
     */
    accountId?: string;
    /**
     * Исключить из расчетов
     * @type {boolean}
     * @memberof TransactionDto
     */
    excluded?: boolean;
}

/**
 * Check if a given object implements the TransactionDto interface.
 */
export function instanceOfTransactionDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransactionDtoFromJSON(json: any): TransactionDto {
    return TransactionDtoFromJSONTyped(json, false);
}

export function TransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : TransactionTypeFromJSON(json['type']),
        'inputType': !exists(json, 'inputType') ? undefined : InputTypeFromJSON(json['inputType']),
        'accountId': !exists(json, 'accountId') ? undefined : json['accountId'],
        'excluded': !exists(json, 'excluded') ? undefined : json['excluded'],
    };
}

export function TransactionDtoToJSON(value?: TransactionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'amount': value.amount,
        'currency': value.currency,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
        'categoryId': value.categoryId,
        'name': value.name,
        'description': value.description,
        'type': TransactionTypeToJSON(value.type),
        'inputType': InputTypeToJSON(value.inputType),
        'accountId': value.accountId,
        'excluded': value.excluded,
    };
}

