/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateReceiptRequest
 */
export interface UpdateReceiptRequest {
    /**
     * Описание чека
     * @type {string}
     * @memberof UpdateReceiptRequest
     */
    description?: string;
    /**
     * ID транзакции для привязки
     * @type {string}
     * @memberof UpdateReceiptRequest
     */
    transactionId?: string | null;
}

/**
 * Check if a given object implements the UpdateReceiptRequest interface.
 */
export function instanceOfUpdateReceiptRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateReceiptRequestFromJSON(json: any): UpdateReceiptRequest {
    return UpdateReceiptRequestFromJSONTyped(json, false);
}

export function UpdateReceiptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReceiptRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'transactionId': !exists(json, 'transactionId') ? undefined : json['transactionId'],
    };
}

export function UpdateReceiptRequestToJSON(value?: UpdateReceiptRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'transactionId': value.transactionId,
    };
}

