/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.finapp.api.controller;

import com.finapp.api.model.ChangePasswordRequest;
import com.finapp.api.model.ChangePasswordResponse;
import com.finapp.api.model.ErrorResponse;
import com.finapp.api.model.JwtResponse;
import com.finapp.api.model.LoginRequest;
import com.finapp.api.model.RegisterRequest;
import com.finapp.api.model.TelegramUserDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-09-24T09:58:51.873684037Z[Etc/UTC]")
@Validated
@Tag(name = "Authentication", description = "the Authentication API")
public interface AuthApi {

    /**
     * POST /auth/login : User login
     *
     * @param loginRequest  (required)
     * @return Successful authentication (status code 200)
     *         or Invalid credentials (status code 401)
     */
    @Operation(
        operationId = "authenticateUser",
        summary = "User login",
        tags = { "Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful authentication", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = JwtResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Invalid credentials", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<JwtResponse> authenticateUser(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    );


    /**
     * POST /auth/telegram : Telegram authentication
     *
     * @param telegramUserDto  (required)
     * @return Successful authentication (status code 200)
     *         or Telegram authentication error (status code 401)
     */
    @Operation(
        operationId = "authenticateWithTelegram",
        summary = "Telegram authentication",
        tags = { "Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful authentication", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = JwtResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Telegram authentication error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/telegram",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<JwtResponse> authenticateWithTelegram(
        @Parameter(name = "TelegramUserDto", description = "", required = true) @Valid @RequestBody TelegramUserDto telegramUserDto
    );


    /**
     * POST /auth/change-password : Change user password
     *
     * @param changePasswordRequest  (required)
     * @return Password successfully changed (status code 200)
     *         or Validation error (status code 400)
     *         or Unauthorized access (status code 401)
     */
    @Operation(
        operationId = "changeUserPassword",
        summary = "Change user password",
        tags = { "Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Password successfully changed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ChangePasswordResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Validation error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized access", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/change-password",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ChangePasswordResponse> changeUserPassword(
        @Parameter(name = "ChangePasswordRequest", description = "", required = true) @Valid @RequestBody ChangePasswordRequest changePasswordRequest
    );


    /**
     * POST /auth/register : User registration
     *
     * @param registerRequest  (required)
     * @return User successfully registered (status code 201)
     *         or Validation error (status code 400)
     */
    @Operation(
        operationId = "registerUser",
        summary = "User registration",
        tags = { "Authentication" },
        responses = {
            @ApiResponse(responseCode = "201", description = "User successfully registered"),
            @ApiResponse(responseCode = "400", description = "Validation error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/register",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> registerUser(
        @Parameter(name = "RegisterRequest", description = "", required = true) @Valid @RequestBody RegisterRequest registerRequest
    );

}
