/* tslint:disable */
/* eslint-disable */
/**
 * FinApp API
 * API for financial application
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@finapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTransactionRequest,
  PagedTransactionsResponse,
  PatchTransactionRequest,
  ProblemDetails,
  TransactionDto,
  TransactionType,
  UpdateTransactionRequest,
} from '../models/index';
import {
    CreateTransactionRequestFromJSON,
    CreateTransactionRequestToJSON,
    PagedTransactionsResponseFromJSON,
    PagedTransactionsResponseToJSON,
    PatchTransactionRequestFromJSON,
    PatchTransactionRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    TransactionDtoFromJSON,
    TransactionDtoToJSON,
    TransactionTypeFromJSON,
    TransactionTypeToJSON,
    UpdateTransactionRequestFromJSON,
    UpdateTransactionRequestToJSON,
} from '../models/index';

export interface CreateTransactionOperationRequest {
    createTransactionRequest: CreateTransactionRequest;
}

export interface DeleteTransactionRequest {
    id: string;
}

export interface GetTransactionByIdRequest {
    id: string;
}

export interface GetTransactionsRequest {
    page?: number;
    size?: number;
    sort?: string;
    categoryId?: string;
    type?: TransactionType;
    startDate?: Date;
    endDate?: Date;
    excluded?: boolean;
}

export interface PatchTransactionOperationRequest {
    id: string;
    ifMatch: string;
    patchTransactionRequest: PatchTransactionRequest;
}

export interface UpdateTransactionOperationRequest {
    id: string;
    updateTransactionRequest: UpdateTransactionRequest;
}

/**
 * TransactionsApi - interface
 * 
 * @export
 * @interface TransactionsApiInterface
 */
export interface TransactionsApiInterface {
    /**
     * Создает новую транзакцию с указанными параметрами. Поддерживает доходы, расходы и переводы между счетами. 
     * @summary Create new transaction
     * @param {CreateTransactionRequest} createTransactionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    createTransactionRaw(requestParameters: CreateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>>;

    /**
     * Создает новую транзакцию с указанными параметрами. Поддерживает доходы, расходы и переводы между счетами. 
     * Create new transaction
     */
    createTransaction(requestParameters: CreateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto>;

    /**
     * Удаляет транзакцию из системы. Операция необратима и влияет на все связанные отчеты и аналитику. 
     * @summary Delete transaction
     * @param {string} id Уникальный идентификатор транзакции
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    deleteTransactionRaw(requestParameters: DeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Удаляет транзакцию из системы. Операция необратима и влияет на все связанные отчеты и аналитику. 
     * Delete transaction
     */
    deleteTransaction(requestParameters: DeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Получает детали конкретной транзакции по её идентификатору. Возвращает ETag для поддержки оптимистичной блокировки. 
     * @summary Get transaction by ID
     * @param {string} id Уникальный идентификатор транзакции
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    getTransactionByIdRaw(requestParameters: GetTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>>;

    /**
     * Получает детали конкретной транзакции по её идентификатору. Возвращает ETag для поддержки оптимистичной блокировки. 
     * Get transaction by ID
     */
    getTransactionById(requestParameters: GetTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto>;

    /**
     * Получить пагинированный список транзакций с возможностью сортировки
     * @summary Get transactions list
     * @param {number} [page] Номер страницы (начиная с 0)
     * @param {number} [size] Размер страницы
     * @param {string} [sort] Критерии сортировки в формате \&#39;field,direction\&#39;
     * @param {string} [categoryId] Фильтр по ID категории
     * @param {TransactionType} [type] Фильтр по типу транзакции
     * @param {Date} [startDate] Начальная дата периода в формате YYYY-MM-DD
     * @param {Date} [endDate] Конечная дата периода в формате YYYY-MM-DD
     * @param {boolean} [excluded] Включать исключенные транзакции
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    getTransactionsRaw(requestParameters: GetTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedTransactionsResponse>>;

    /**
     * Получить пагинированный список транзакций с возможностью сортировки
     * Get transactions list
     */
    getTransactions(requestParameters: GetTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedTransactionsResponse>;

    /**
     * Частичное обновление транзакции с поддержкой оптимистичной блокировки. Обновляет только переданные поля, остальные остаются без изменений. 
     * @summary Partially update transaction
     * @param {string} id Уникальный идентификатор транзакции
     * @param {string} ifMatch ETag для оптимистичной блокировки
     * @param {PatchTransactionRequest} patchTransactionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    patchTransactionRaw(requestParameters: PatchTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>>;

    /**
     * Частичное обновление транзакции с поддержкой оптимистичной блокировки. Обновляет только переданные поля, остальные остаются без изменений. 
     * Partially update transaction
     */
    patchTransaction(requestParameters: PatchTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto>;

    /**
     * Полное обновление существующей транзакции. Заменяет все поля транзакции новыми значениями. 
     * @summary Update transaction
     * @param {string} id 
     * @param {UpdateTransactionRequest} updateTransactionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApiInterface
     */
    updateTransactionRaw(requestParameters: UpdateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>>;

    /**
     * Полное обновление существующей транзакции. Заменяет все поля транзакции новыми значениями. 
     * Update transaction
     */
    updateTransaction(requestParameters: UpdateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto>;

}

/**
 * 
 */
export class TransactionsApi extends runtime.BaseAPI implements TransactionsApiInterface {

    /**
     * Создает новую транзакцию с указанными параметрами. Поддерживает доходы, расходы и переводы между счетами. 
     * Create new transaction
     */
    async createTransactionRaw(requestParameters: CreateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>> {
        if (requestParameters.createTransactionRequest === null || requestParameters.createTransactionRequest === undefined) {
            throw new runtime.RequiredError('createTransactionRequest','Required parameter requestParameters.createTransactionRequest was null or undefined when calling createTransaction.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/transactions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTransactionRequestToJSON(requestParameters.createTransactionRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDtoFromJSON(jsonValue));
    }

    /**
     * Создает новую транзакцию с указанными параметрами. Поддерживает доходы, расходы и переводы между счетами. 
     * Create new transaction
     */
    async createTransaction(requestParameters: CreateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto> {
        const response = await this.createTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удаляет транзакцию из системы. Операция необратима и влияет на все связанные отчеты и аналитику. 
     * Delete transaction
     */
    async deleteTransactionRaw(requestParameters: DeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteTransaction.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/transactions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Удаляет транзакцию из системы. Операция необратима и влияет на все связанные отчеты и аналитику. 
     * Delete transaction
     */
    async deleteTransaction(requestParameters: DeleteTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTransactionRaw(requestParameters, initOverrides);
    }

    /**
     * Получает детали конкретной транзакции по её идентификатору. Возвращает ETag для поддержки оптимистичной блокировки. 
     * Get transaction by ID
     */
    async getTransactionByIdRaw(requestParameters: GetTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getTransactionById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/transactions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDtoFromJSON(jsonValue));
    }

    /**
     * Получает детали конкретной транзакции по её идентификатору. Возвращает ETag для поддержки оптимистичной блокировки. 
     * Get transaction by ID
     */
    async getTransactionById(requestParameters: GetTransactionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto> {
        const response = await this.getTransactionByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получить пагинированный список транзакций с возможностью сортировки
     * Get transactions list
     */
    async getTransactionsRaw(requestParameters: GetTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedTransactionsResponse>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.categoryId !== undefined) {
            queryParameters['categoryId'] = requestParameters.categoryId;
        }

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        if (requestParameters.startDate !== undefined) {
            queryParameters['startDate'] = (requestParameters.startDate as any).toISOString().substring(0,10);
        }

        if (requestParameters.endDate !== undefined) {
            queryParameters['endDate'] = (requestParameters.endDate as any).toISOString().substring(0,10);
        }

        if (requestParameters.excluded !== undefined) {
            queryParameters['excluded'] = requestParameters.excluded;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/transactions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedTransactionsResponseFromJSON(jsonValue));
    }

    /**
     * Получить пагинированный список транзакций с возможностью сортировки
     * Get transactions list
     */
    async getTransactions(requestParameters: GetTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedTransactionsResponse> {
        const response = await this.getTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Частичное обновление транзакции с поддержкой оптимистичной блокировки. Обновляет только переданные поля, остальные остаются без изменений. 
     * Partially update transaction
     */
    async patchTransactionRaw(requestParameters: PatchTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling patchTransaction.');
        }

        if (requestParameters.ifMatch === null || requestParameters.ifMatch === undefined) {
            throw new runtime.RequiredError('ifMatch','Required parameter requestParameters.ifMatch was null or undefined when calling patchTransaction.');
        }

        if (requestParameters.patchTransactionRequest === null || requestParameters.patchTransactionRequest === undefined) {
            throw new runtime.RequiredError('patchTransactionRequest','Required parameter requestParameters.patchTransactionRequest was null or undefined when calling patchTransaction.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.ifMatch !== undefined && requestParameters.ifMatch !== null) {
            headerParameters['If-Match'] = String(requestParameters.ifMatch);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/transactions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchTransactionRequestToJSON(requestParameters.patchTransactionRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDtoFromJSON(jsonValue));
    }

    /**
     * Частичное обновление транзакции с поддержкой оптимистичной блокировки. Обновляет только переданные поля, остальные остаются без изменений. 
     * Partially update transaction
     */
    async patchTransaction(requestParameters: PatchTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto> {
        const response = await this.patchTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Полное обновление существующей транзакции. Заменяет все поля транзакции новыми значениями. 
     * Update transaction
     */
    async updateTransactionRaw(requestParameters: UpdateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateTransaction.');
        }

        if (requestParameters.updateTransactionRequest === null || requestParameters.updateTransactionRequest === undefined) {
            throw new runtime.RequiredError('updateTransactionRequest','Required parameter requestParameters.updateTransactionRequest was null or undefined when calling updateTransaction.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/transactions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTransactionRequestToJSON(requestParameters.updateTransactionRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDtoFromJSON(jsonValue));
    }

    /**
     * Полное обновление существующей транзакции. Заменяет все поля транзакции новыми значениями. 
     * Update transaction
     */
    async updateTransaction(requestParameters: UpdateTransactionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDto> {
        const response = await this.updateTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
