name: Build and Publish API Libraries

on:
  push:
    paths:
      - 'api-docs/**'
      - 'openapi.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'api-docs/**'
      - 'openapi.yaml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          # Try npm ci first, fallback to npm install if lock file is out of sync
          if ! npm ci --engine-strict=false; then
            echo "npm ci failed, falling back to npm install..."
            npm install --engine-strict=false
            echo "Lock file was updated, committing changes..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add package-lock.json
            git commit -m "chore: update package-lock.json after dependency changes" || echo "No lock file changes to commit"
          fi

      - name: Lint and validate OpenAPI spec
        run: npm run validate

      - name: Debug - Before generation
        run: |
          echo "=== Debug: Before generation ==="
          ls -la generated/ || echo "generated/ does not exist yet"
          ls -la packages/ || echo "packages/ does not exist yet"

      - name: Generate code and prepare packages
        run: npm run prepare:packages

      - name: Debug - After generation
        run: |
          echo "=== Debug: After generation ==="
          echo "Generated frontend models:"
          ls -la generated/frontend/src/models/ || echo "generated/frontend/src/models/ not found"
          echo "Package frontend models:"
          ls -la packages/frontend-api/src/models/ || echo "packages/frontend-api/src/models/ not found"
          echo "Generated frontend files count:"
          find generated/frontend/src/models/ -name "*.ts" | wc -l || echo "No TS files found"
          echo "Package frontend files count:"
          find packages/frontend-api/src/models/ -name "*.ts" | wc -l || echo "No TS files found"

      - name: Build frontend package
        run: npm run build:frontend-package

      - name: Determine version bump
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "bump=patch" >> $GITHUB_OUTPUT
          else
            echo "bump=none" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and sync packages
        if: steps.version.outputs.bump != 'none'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Add any generated files to git before versioning
          git add .
          git commit -m "chore: update generated code" || echo "No changes to commit"

          # Sync versions first to get OpenAPI version
          npm run update:package-versions

          # Commit any changes made by sync-versions.js (frontend/backend packages)
          git add .
          git commit -m "chore: sync package versions" || echo "No version sync changes to commit"

          # Then bump version
          npm run version:${{ steps.version.outputs.bump }}

          # Get the new version and set as environment variable
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "📦 New version: ${NEW_VERSION}"

      - name: Publish Frontend Package to GitHub Packages
        if: steps.version.outputs.bump != 'none'
        run: |
          echo "Publishing frontend package to GitHub Packages..."
          cd packages/frontend-api
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          echo "@sergey-videtskikh:registry=https://npm.pkg.github.com" >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Maven settings
        if: steps.version.outputs.bump != 'none'
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Publish Backend Package to GitHub Packages
        if: steps.version.outputs.bump != 'none'
        run: npm run publish:backend

      - name: Create Release
        if: steps.version.outputs.bump != 'none'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          body: |
            ## API Libraries Release v${{ env.NEW_VERSION }}

            ### Published Packages:
            - **Backend (Maven)**: `com.finapp:finapp-api-client:${{ env.NEW_VERSION }}`
            - **Frontend (NPM)**: `@sergey-videtskikh/finapp-api-client@${{ env.NEW_VERSION }}`

            ### Usage:

            #### Backend (Maven)
            ```xml
            <dependency>
                <groupId>com.finapp</groupId>
                <artifactId>finapp-api-client</artifactId>
                <version>${{ env.NEW_VERSION }}</version>
            </dependency>
            ```

            #### Frontend (NPM)
            ```bash
            npm install @sergey-videtskikh/finapp-api-client@${{ env.NEW_VERSION }}
            ```

            ### Changes:
            - Updated API models and interfaces
            - Synced with latest OpenAPI specification
          draft: false
          prerelease: false

      - name: Commit version updates
        if: steps.version.outputs.bump != 'none'
        run: |
          git add .
          git commit -m "chore: bump version to v${{ env.NEW_VERSION }}" || exit 0
          git push